### ISSUE TITLE
Fix bug in optimism gas oracle

### ISSUE THREAD

**Issue by seunlanlege** [polytope-labs/hyperbridge#336]
The Tesseract relayer has a sub module referred to as the gas Oracle. This module is responsible for estimating the gas price, gas cost, and USD equivalent for cross chain transactions. 

It is currently broken for the optimism chain, ever since the migration to blobs it has been broken and it over estimates the gas cost, 

Which is apparently now a multidimensional value comprised of the L1 blob fee and gas costs as well as the L2 execution fee.

In order for relayers to correctly estimate the costs of the optimism transactions. This estimation process must be investigated and fixed.

**Comment by mahmudsudo** [comment]
Hi can I take on this ?

**Comment by seunlanlege** [comment]
> Hi can I take on this ?

Yeah definitely!

**Comment by sylvaincormier** [comment]
Hi! Since it appears there hasn't been any progress on this issue, I'd like to take it on.

**Comment by Wizdave97** [comment]
Current implementation of the gas estimate for opstack is identical to what's implemented in the optimism-sdk

Tesseract estimates are approximately correct as shown from the samples in the doc
https://docs.google.com/document/d/1-1Eo-5viezojO3EjPlYMVpgTx3zMVFxDWitG9aZnoDc/edit?tab=t.0

The issue with overestimation was fixed by this PR https://github.com/polytope-labs/hyperbridge/pull/337
